# const file for language
# debug info is excluded

TITLE_SAVE_PATH_SEL="選擇人物存檔文件"
TITLE_DYNC_PATH_SEL="選擇動態數據文件"
TITLE_DATA_PATH_SEL="選擇遊戲數據文件"
TITLE_CHAR_DATA="人物屬性與數據"

TXT_SAVE_PATH="人物存檔文件位置 (*.GRP) :"
TXT_DYNC_PATH="動態數據文件位置 (*.GRP) :"
TXT_DATA_PATH="遊戲數據文件位置 (Z.dat) :"

TXT_CHAR_DATA="人物數據"
TXT_NAME="姓 名"
TXT_POSITION="位 置"
TXT_ATTACK="武 功\n(最多十種)"
TXT_LEVEL="等 級\n(1~10)"
TXT_TEAM="成 員\n(最多六人)"
TXT_MAIN_SETTING="主角設定"
TXT_MAIN_DESC="改變主角姓名\n會同時改變主角居名稱"
TXT_MEMBER_LST="隊友列表"
TXT_MEMBER_DESC="隊友說明"
TXT_ATTACK_LST="武功列表"
TXT_MERC_POSITION="出現在客棧地圖中"
TXT_MERCHANT_POS="韋小寶所在"
TXT_VENOM_ENHANCE="毒性增強"
TXT_VENOM_DIVISOR="中毒除數"
TXT_SAVE_LOADED="全部數據讀取完畢"
TXT_SAVE_REFRESHED="全部數據更新完畢"
TXT_SAVE_WRITEN="成功寫入所有數據"

ERR_SAVE_NOT_EXIST="錯誤: R*.GRP文件不存在"
ERR_DYNC_NOT_EXIST="錯誤: D*.GRP文件不存在"
ERR_DATA_NOT_EXIST="錯誤: Z.dat數據文件不存在"

BTN_READ="讀 取"
BTN_CLOSE="關 閉"
BTN_SELECT="選 擇"
BTN_RETURN="返 回"
BTN_WRITE="寫 入"
BTN_REFRESH="刷 新"
