"""
This is a setup.py script generated by py2applet

Usage:
    py2applet --make-setup lengend_modify.py
    rm -rf build dist
    ./venv/bin/python setup.py py2app

Test:
    open -a dist/lengend_modify.app

Make a dmg:
    Open Disk Utility
    File -> New Image -> Blank Image -> read-write image
    open the blank dmg file
    Make an Applications alias, remove the alias suffix, and move it into the dmg file
    Open the dmg file and create a hidden folder called .background inside it
	Copy your background image to that folder
	(You need to include the background file in the hidden folder in the dmg file.)
	Set that image as the folder's background image using Finder
    Drag App file and Applications alias into this dmg file
    Eject out dmg
    Open Disk Utility
    Images -> Convert -> Select dmg -> read-only file

"""

from setuptools import setup

APP = ['lengend_modify.py']
APP_NAME = '金庸群侠传DOS版修改器'
DATA_FILES = ['img', 'snd', 'data.json']
OPTIONS = {
    'iconfile': 'img/icon.icns',  # optional
}

setup(
    app=APP,
    name=APP_NAME,
    version='3.0.1',
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
